const express = require('express');
const app = express();

const dareCommands = [
  "Send a funny selfie.",
  "Text a friend using only emojis.",
  "Change your profile picture to something silly for an hour.",
  "Send a voice message singing your favorite song.",
  "Call someone and say 'I love you' in a funny accent.",
  "Send a GIF that shows how you feel right now.",
  "Send a message using only one word.",
  "Type your name backward and send it.",
  "Send a message pretending you are a celebrity.",
  "Send a random emoji and explain why you picked it.",
  "Text a friend asking for a funny joke.",
  "Send a message with all capital letters.",
  "Message someone telling them you dreamt about them.",
  "Send a funny nickname for yourself.",
  "Text a friend asking 'What’s the weirdest thing you ate?'",
  "Message someone using only song lyrics.",
  "Send a silly selfie with a funny face.",
  "Text a friend and say ‘Guess what?’ then send a random fact.",
  "Send a message pretending you are a robot.",
  "Tell someone you have a secret but don’t reveal it.",
  "Send a message using only emojis representing your day.",
  "Text a friend and say you’re late because of a llama.",
  "Send a voice note telling a funny story.",
  "Send a message with a random compliment.",
  "Text ‘I’m stuck in an elevator’ just for fun.",
  "Message a friend saying you’ve joined a secret club.",
  "Send a funny pun to someone.",
  "Text ‘Did you know I can speak dolphin?’",
  "Send the last photo in your gallery and explain it.",
  "Send an exaggerated reaction emoji to a normal message.",
  "Text someone and say ‘You won a free hug!’",
  "Send a message with an invented word.",
  "Message someone with a funny movie quote.",
  "Send a voice message trying to do an impression.",
  "Text a friend ‘I’m training to be a ninja’",
  "Send a funny meme link.",
  "Message someone you are an alien visiting Earth.",
  "Text a friend using only rhymes.",
  "Send a random fact and see if they believe it.",
  "Message ‘I’m practicing my stand-up comedy’",
  "Send a funny birthday wish even if it’s not their birthday.",
  "Text a friend ‘I lost my pet dragon’",
  "Send a message pretending to be a news reporter.",
  "Send a voice note with your best cartoon character voice.",
  "Message someone ‘Can you keep a secret?’",
  "Text ‘I just saw a unicorn!’",
  "Send a funny nickname for your best friend.",
  "Message someone ‘I’m an undercover spy’",
  "Send a message ending every word with ‘-izzle’.",
  "Text ‘Guess who just learned to moonwalk?’",
  "Send an audio clip of you laughing weirdly.",
  "Message a friend ‘I’m stuck in traffic with a llama’",
  "Send a silly riddle.",
  "Text a friend your favorite silly dance move.",
  "Send a message like a pirate for 1 minute.",
  "Message someone a random compliment.",
  "Send a voicemail singing your favorite cartoon theme song.",
  "Text ‘I’m secretly a superhero’",
  "Send a quirky fact about yourself.",
  "Message someone ‘I’m lost in the supermarket’",
  "Send a voice note saying ‘I’m in a secret mission.’",
  "Text a friend ‘Do you believe in ghosts?’",
  "Send a funny tongue twister.",
  "Message ‘I’m a wizard learning new spells!’",
  "Text a friend ‘I’m hiding from ninjas’",
  "Send a message pretending you’re a famous chef.",
  "Message someone ‘I accidentally joined a circus’",
  "Send a silly joke.",
  "Text a friend ‘My socks are secretly magical’",
  "Send a voice note doing animal sounds.",
  "Message ‘I’m inventing a new dance move.’",
  "Text ‘I just found a treasure map!’",
  "Send a funny selfie with a silly hat.",
  "Message someone ‘I’m the king/queen of karaoke.’",
  "Send a silly excuse for being late.",
  "Text ‘I’m training my dog to talk.’",
  "Send a random emoji and say it’s your spirit animal.",
  "Message someone ‘I just saw a UFO!’",
  "Text ‘I can’t stop dancing!’",
  "Send a voice note counting backward from 20.",
  "Message ‘I’m a secret agent on vacation.’",
  "Text a friend ‘Want to join my secret club?’",
  "Send a funny movie quote.",
  "Message someone ‘I’m undercover at a party.’",
  "Send a silly face emoji and don’t explain it.",
  "Text ‘I’m writing a book about llamas.’",
  "Send a message pretending to be a robot assistant.",
  "Message ‘I just invented a new holiday!’",
  "Text a friend ‘Can you keep a plant alive for me?’",
  "Send a voice note where you falsify a famous news story.",
  "Message someone ‘I’m a time traveler from the future.’"
];

app.get('/', (req, res) => {
  const randomIndex = Math.floor(Math.random() * dareCommands.length);
  const question = dareCommands[randomIndex];
  res.json({
    data: {
      question: question
    }
  });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Dare service is running on port ${PORT}`);
});
